kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-provisioner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csi-provisioner
  template:
    metadata:
      labels:
        app: csi-provisioner
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: csi-provisioner
          image: {{ .Values.virium.csiProvisioner.image.repository }}:{{ .Values.virium.csiProvisioner.image.tag | default .Chart.AppVersion }}
          args: {{- toYaml .Values.virium.csiProvisioner.args | nindent 10 }}          
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 20
          env:
          - name: ADDRESS
            value: /csi/csi.sock
          volumeMounts:
          - name: socket-dir
            mountPath: /csi  
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/virium.csi.virer.net
          type: DirectoryOrCreate
        name: socket-dir            