virium:
  virium:
    args:
    - --nodeid=$(NODE_ID)
    - --endpoint=$(CSI_ENDPOINT)
    - --apiurl=$(API_URL)
    - --initiatorname=$(INITIATOR)
    - --api_username=$(API_USERNAME)
    - --api_password=$(API_PASSWORD)
    - --v=$(DEBUG)
    image:
      repository: docker.io/scaps/virium-csi-driver-iscsi
      tag: v0.2.2.7
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 300Mi
      requests:
        cpu: 10m
        memory: 20Mi
  csiResizer:
    image: 
      repository: registry.k8s.io/sig-storage/csi-resizer
      tag: v1.12.0
    args:
    - "--v=2"
    - "--csi-address=$(ADDRESS)"
    - "--leader-election"
    - "--http-endpoint=:8080"
  csiSnapshotter:
    image: 
      repository: registry.k8s.io/sig-storage/csi-snapshotter
      tag: v8.2.0
    args:
    - "--v=2"
    - "--csi-address=$(ADDRESS)"
    - "--leader-election"
    - "--http-endpoint=:8080"    
  csiProvisioner:
    args:
    - -v=2
    - --csi-address=$(ADDRESS)
    - --leader-election
    - --extra-create-metadata=true
    - --immediate-topology=true
    - --feature-gates=HonorPVReclaimPolicy=true
    - --timeout=1200s
    - --retry-interval-max=15m
    - --node-deployment-immediate-binding=true
    - --http-endpoint=:8080
    env:
      address: /csi/csi.sock
    image:
      repository: registry.k8s.io/sig-storage/csi-provisioner
      tag: v5.2.0
    resources:
      limits:
        memory: 400Mi
      requests:
        cpu: 10m
        memory: 20Mi
  csiAttacher:
    image: 
      repository: registry.k8s.io/sig-storage/csi-attacher
      tag: v3.5.0
    args:
    - "--v=5"
    - "--csi-address=$(ADDRESS)"
    - "--leader-election"
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 20Mi
  livenessProbe:
    args:
    - --csi-address=/csi/csi.sock
    - --probe-timeout=3s
    - --health-port=29753
    - --v=2
    image:
      repository: registry.k8s.io/sig-storage/livenessprobe
      tag: v2.10.0
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
  nodeDriverRegistrar:
    args:
    - --v=2
    - --csi-address=/csi/csi.sock
    - --kubelet-registration-path=/var/lib/kubelet/plugins/virium.csi.virer.net/csi.sock
    containerSecurityContext:
      privileged: true
    image:
      repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
      tag: v2.8.0
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 20Mi
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccount:
    annotations: {}
viriumConfig:
  apiUsername: "virium_api_username"
  apiPassword: "virium_api_password"
  apiurl: "http://virium-api-fqdn.domain.tld:8787"
  initiator: "iqn.2025-04.net.virer.virium.test:target1"
  debug: "2"
